### ISSUE TITLE
初始化英雄克制矩阵

### ISSUE THREAD

**Issue by windybirth** [windybirth/windy10v10ai-cloud#221]
1. 定义克制矩阵的数据结构
在Firestore中创建一个集合 counter_matrix，存储每个英雄对其他英雄的克制得分，以及EWMA算法所需的历史数据（如 current_score, ewma_score, alpha, last_score）。

```yaml
collections:
  "counter_matrix"  # 集合名称
    document: "HeroA"  # 文档名称为英雄名称
      fields:
        "HeroB":
          "current_score": 0.5  # HeroA 对 HeroB 的当前克制得分
          "ewma_score": 0.45    # 基于EWMA计算的克制得分
          "alpha": 0.3          # EWMA的平滑因子
          "last_score": 0.4     # 上一次更新时的得分
        "HeroC":
          "current_score": 0.4
          "ewma_score": 0.38
          "alpha": 0.3
          "last_score": 0.35
    document: "HeroB"
      fields:
        "HeroA":
          "current_score": 0.6
          "ewma_score": 0.55
          "alpha": 0.3
          "last_score": 0.52
```
2. 初始化数据
初始化Firestore中的克制矩阵数据，确保每个英雄对的初始克制得分合理。
